# Large Model Configuration (Run #6)
# New attention architecture may tackle gradient issues and allow to go beyond 47% plateau
# Hyperparameter are the same as Run #4
model:
  attention_embed_dim: 256
  attention_num_heads: 8
  attention_num_layers: 3
  use_attention: true
  use_silu: true

ppo:
  # lower lr to be more conservative
  learning_rate: 1.0e-5
  min_learning_rate: 1.0e-6
  
  # Keep batch size at 2048
  batch_size: 2048
  n_steps: 2048
  n_epochs: 6
  
  # PPO hyperparameters 
  gamma: 0.98
  gae_lambda: 0.95
  ent_coef: 0.03
  vf_coef: 0.8
  clip_range: 0.15
  target_kl: 0.01

training:
  total_timesteps: 30000000
  checkpoint_freq: 10000
  n_envs: 32
  use_batched_env: true
  device: "auto"
  frozen_opponent_update_freq: 75000
  adaptive_frozen_opponent: true
  target_win_rate: 0.55

environment:
  max_turns: 99
  max_actions_per_turn: 50
  max_total_actions: 500

paths:
  simple_deck_path: "simple_deck.json"
  meta_deck_path: "meta_deck.json"
  save_path: "models/rl_bot_large_3"
  checkpoint_dir: "./checkpoints/large_3/"
  tensorboard_dir: "./logs/"
  resume_path: null

